services:
  - type: web
    name: fichos-bienestar
    env: docker
    region: ohio
    plan: starter
    branch: main
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "Día del Aprendiz"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://fichos-bienestar.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: fichos-db
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromDatabase:
          name: fichos-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: fichos-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: fichos-db
          property: password

databases:
  - name: fichos-db
    databaseName: fichos
    user: fichos_user
    plan: starter
    region: ohio
